source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'AdvertiseAdcolony_Example' do
  platform :ios, '7.0'
  pod 'AdvertiseAdcolony', :path => '../'

  target 'AdvertiseAdcolony_Tests' do
    inherit! :search_paths

    
  end
end
